# Generated by Django 5.0.1 on 2024-04-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_stockrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('value_text', 'Text'), ('value_integer', 'Integer'), ('value_float', 'Float'), ('value_option', 'Option'), ('value_multi_option', 'Multi Option')], default='value_text', max_length=20),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('value_text', 'Text'), ('value_integer', 'Integer'), ('value_float', 'Float'), ('value_option', 'Option'), ('value_multi_option', 'Multi Option')], default='value_text', max_length=20),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productattribute'),
        ),
    ]
